# Generated by Django 4.2.5 on 2023-10-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Address', models.CharField(max_length=500)),
                ('JOB', models.CharField(max_length=100)),
                ('Salary', models.IntegerField()),
            ],
        ),
    ]
